# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb8a719448a4cf52f32a239a3537764976358a87a3e819dc77edceb744b348cdf9c6cc5a3acc4eeaf2e0c899997ee8b474cc12d9238e791bf268c3631698de6f

test:
  secret_key_base: 5d57d46b286ee3a8018a8b475faac0be6ac2ca0c8ce39b0c56c70c32ec25fe62ef9d99e8c9780fc57bf13484a07c1658f8a63b2b7c4193c51da887bb5c8c0183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
